name: rehana_dashboared
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ✅ Correct localization package
  flutter_localizations:
    sdk: flutter
#  intl: ^0.19.0

  # ✅ Core packages
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
#  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  loading_animation_widget: ^1.3.0
  dio_cache_interceptor: ^4.0.3
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.4
  easy_date_timeline: ^2.0.9
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/logorehana.png
    - assets/photo/
    - images/photo.png

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Black.ttf
        - asset: assets/fonts/Alexandria-Bold.ttf
        - asset: assets/fonts/Alexandria-ExtraLight.ttf
        - asset: assets/fonts/Alexandria-Light.ttf
        - asset: assets/fonts/Alexandria-Medium.ttf
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-SemiBold.ttf
        - asset: assets/fonts/Alexandria-Thin.ttf

flutter_intl:
  enabled: true

flutter_launcher_icons:
  image_path: "images/icon/rehana.png"

  android: "launcher_icon"
  min_sdk_android: 21

  ios: true
  remove_alpha_channel_ios: true

  web:
    generate: true
    image_path: "images/icon/rehana.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

  windows:
    generate: true
    image_path: "images/icon/rehana.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "images/icon/rehana.png"
